* slash in node selector attribute value results in 500 internal server error
because split('/')  is used instead of proper parser


* easy to cause an exception with invalid requests
for example, instead of GET send XXX:

Traceback (most recent call last):
  File "/usr/lib/python2.5/site-packages/twisted/web2/server.py", line 296, in <
lambda>
    d.addCallback(lambda res, req: res.renderHTTP(req), self)
  File "/usr/lib/python2.5/site-packages/xcap/authentication.py", line 231, in renderHTTP
    d.addCallback(_renderResource)
  File "/usr/lib/python2.5/site-packages/twisted/internet/defer.py", line 195, in addCallback
    callbackKeywords=kw)
  File "/usr/lib/python2.5/site-packages/twisted/internet/defer.py", line 186, in addCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/usr/lib/python2.5/site-packages/twisted/internet/defer.py", line 328, in _runCallbacks
    self.result = callback(self.result, *args, **kw)
  File "/usr/lib/python2.5/site-packages/xcap/authentication.py", line 210, in _renderResource
    return resource.renderHTTP(request)
  File "/usr/lib/python2.5/site-packages/xcap/server.py", line 114, in renderHTTP
    d = resource.renderHTTP(request)
  File "/usr/lib/python2.5/site-packages/xcap/resource.py", line 32, in renderHTTP
    d.addCallback(self.sendResponse)
exceptions.AttributeError: 'Response' object has no attribute 'addCallback'

* uri validation of several kinds (the same is true for resource-lists)
what's intentionally skipped:
* global scope of uri attr in <service> and building /global/index (supposed
to be used by rls, RLS module in openser doesn't use it)

